// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: logistics/supplychain/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the supplychain module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params        Params     `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	ProductList   []Product  `protobuf:"bytes,2,rep,name=productList,proto3" json:"productList"`
	ProductCount  uint64     `protobuf:"varint,3,opt,name=productCount,proto3" json:"productCount,omitempty"`
	ShipmentList  []Shipment `protobuf:"bytes,4,rep,name=shipmentList,proto3" json:"shipmentList"`
	ShipmentCount uint64     `protobuf:"varint,5,opt,name=shipmentCount,proto3" json:"shipmentCount,omitempty"`
	OrderList     []Order    `protobuf:"bytes,6,rep,name=orderList,proto3" json:"orderList"`
	OrderCount    uint64     `protobuf:"varint,7,opt,name=orderCount,proto3" json:"orderCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d38431d2900347d1, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetProductList() []Product {
	if m != nil {
		return m.ProductList
	}
	return nil
}

func (m *GenesisState) GetProductCount() uint64 {
	if m != nil {
		return m.ProductCount
	}
	return 0
}

func (m *GenesisState) GetShipmentList() []Shipment {
	if m != nil {
		return m.ShipmentList
	}
	return nil
}

func (m *GenesisState) GetShipmentCount() uint64 {
	if m != nil {
		return m.ShipmentCount
	}
	return 0
}

func (m *GenesisState) GetOrderList() []Order {
	if m != nil {
		return m.OrderList
	}
	return nil
}

func (m *GenesisState) GetOrderCount() uint64 {
	if m != nil {
		return m.OrderCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "logistics.supplychain.GenesisState")
}

func init() {
	proto.RegisterFile("logistics/supplychain/genesis.proto", fileDescriptor_d38431d2900347d1)
}

var fileDescriptor_d38431d2900347d1 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0x3a, 0x41,
	0x14, 0xc0, 0x77, 0xfe, 0xfa, 0x37, 0x1c, 0xed, 0xd0, 0x50, 0x20, 0x92, 0xa3, 0x99, 0x07, 0xe9,
	0xb0, 0x0b, 0x76, 0xe8, 0x2a, 0x06, 0x45, 0x10, 0x14, 0x7a, 0xeb, 0xb6, 0xe9, 0xb0, 0x0e, 0xe8,
	0xce, 0xb0, 0x33, 0x42, 0x7e, 0x8a, 0xfa, 0x18, 0x1d, 0xfb, 0x18, 0x1e, 0x3d, 0x76, 0x8a, 0xd0,
	0x43, 0x5f, 0x23, 0x7c, 0x33, 0x9b, 0xbb, 0xb0, 0x7b, 0x59, 0xe6, 0x3d, 0x7e, 0xef, 0xfd, 0xde,
	0xdb, 0x87, 0xcf, 0x67, 0x22, 0xe0, 0x4a, 0xf3, 0xb1, 0xf2, 0xd4, 0x42, 0xca, 0xd9, 0x72, 0x3c,
	0xf5, 0x79, 0xe8, 0x05, 0x2c, 0x64, 0x8a, 0x2b, 0x57, 0x46, 0x42, 0x0b, 0x72, 0xf2, 0x07, 0xb9,
	0x09, 0xa8, 0x7e, 0xe4, 0xcf, 0x79, 0x28, 0x3c, 0xf8, 0x1a, 0xb2, 0x7e, 0x1c, 0x88, 0x40, 0xc0,
	0xd3, 0xdb, 0xbd, 0x6c, 0xb6, 0x9d, 0x2d, 0x91, 0x7e, 0xe4, 0xcf, 0xad, 0xa3, 0x9e, 0x33, 0x88,
	0x8c, 0xc4, 0x64, 0x31, 0xd6, 0x16, 0xea, 0x64, 0x43, 0x6a, 0xca, 0xe5, 0x9c, 0x85, 0x31, 0x75,
	0x96, 0x4d, 0x89, 0x68, 0xc2, 0x22, 0x83, 0xb4, 0x5f, 0x0b, 0xb8, 0x7a, 0x6b, 0x76, 0x1c, 0x69,
	0x5f, 0x33, 0xd2, 0xc7, 0x25, 0x33, 0x4e, 0x0d, 0xb5, 0x50, 0xb7, 0xd2, 0x6b, 0xb8, 0x99, 0x3b,
	0xbb, 0x8f, 0x00, 0x0d, 0xca, 0xab, 0xaf, 0xa6, 0xf3, 0xfe, 0xf3, 0x71, 0x81, 0x86, 0xb6, 0x8e,
	0xdc, 0xe0, 0x8a, 0x1d, 0xf6, 0x9e, 0x2b, 0x5d, 0xfb, 0xd7, 0x2a, 0x74, 0x2b, 0x3d, 0x9a, 0xd7,
	0xc6, 0x90, 0x83, 0xe2, 0xae, 0xcf, 0x30, 0x59, 0x48, 0xda, 0xb8, 0x6a, 0xc3, 0x6b, 0xb1, 0x08,
	0x75, 0xad, 0xd0, 0x42, 0xdd, 0xe2, 0x30, 0x95, 0x23, 0x77, 0xb8, 0x1a, 0xef, 0x0c, 0xb2, 0x22,
	0xc8, 0x9a, 0x39, 0xb2, 0x91, 0x45, 0xad, 0x2d, 0x55, 0x4a, 0x3a, 0xf8, 0x30, 0x8e, 0x8d, 0xef,
	0x3f, 0xf8, 0xd2, 0x49, 0xd2, 0xc7, 0x65, 0xf8, 0x7d, 0x60, 0x2b, 0x81, 0xed, 0x34, 0xc7, 0xf6,
	0xb0, 0xe3, 0xac, 0x6a, 0x5f, 0x44, 0x28, 0xc6, 0x10, 0x18, 0xc9, 0x01, 0x48, 0x12, 0x99, 0xc1,
	0xd5, 0x6a, 0x43, 0xd1, 0x7a, 0x43, 0xd1, 0xf7, 0x86, 0xa2, 0xb7, 0x2d, 0x75, 0xd6, 0x5b, 0xea,
	0x7c, 0x6e, 0xa9, 0xf3, 0xd4, 0xd8, 0x9f, 0xf3, 0x25, 0x75, 0x50, 0xbd, 0x94, 0x4c, 0x3d, 0x97,
	0xe0, 0xa2, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0x7b, 0x3f, 0x92, 0xca, 0x02, 0x00,
	0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OrderCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.OrderCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.OrderList) > 0 {
		for iNdEx := len(m.OrderList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.ShipmentCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ShipmentCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ShipmentList) > 0 {
		for iNdEx := len(m.ShipmentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ShipmentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ProductCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ProductCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProductList) > 0 {
		for iNdEx := len(m.ProductList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProductList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ProductList) > 0 {
		for _, e := range m.ProductList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ProductCount != 0 {
		n += 1 + sovGenesis(uint64(m.ProductCount))
	}
	if len(m.ShipmentList) > 0 {
		for _, e := range m.ShipmentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ShipmentCount != 0 {
		n += 1 + sovGenesis(uint64(m.ShipmentCount))
	}
	if len(m.OrderList) > 0 {
		for _, e := range m.OrderList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.OrderCount != 0 {
		n += 1 + sovGenesis(uint64(m.OrderCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductList = append(m.ProductList, Product{})
			if err := m.ProductList[len(m.ProductList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductCount", wireType)
			}
			m.ProductCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProductCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShipmentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShipmentList = append(m.ShipmentList, Shipment{})
			if err := m.ShipmentList[len(m.ShipmentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShipmentCount", wireType)
			}
			m.ShipmentCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShipmentCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderList = append(m.OrderList, Order{})
			if err := m.OrderList[len(m.OrderList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderCount", wireType)
			}
			m.OrderCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
