// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: logistics/supplychain/shipment.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Shipment struct {
	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShipmentId string `protobuf:"bytes,2,opt,name=shipmentId,proto3" json:"shipmentId,omitempty"`
	ProductId  string `protobuf:"bytes,3,opt,name=productId,proto3" json:"productId,omitempty"`
	Sender     string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver   string `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Status     string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Location   string `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp  string `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (m *Shipment) Reset()         { *m = Shipment{} }
func (m *Shipment) String() string { return proto.CompactTextString(m) }
func (*Shipment) ProtoMessage()    {}
func (*Shipment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ccdafbfa7d76829, []int{0}
}
func (m *Shipment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Shipment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Shipment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Shipment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shipment.Merge(m, src)
}
func (m *Shipment) XXX_Size() int {
	return m.Size()
}
func (m *Shipment) XXX_DiscardUnknown() {
	xxx_messageInfo_Shipment.DiscardUnknown(m)
}

var xxx_messageInfo_Shipment proto.InternalMessageInfo

func (m *Shipment) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shipment) GetShipmentId() string {
	if m != nil {
		return m.ShipmentId
	}
	return ""
}

func (m *Shipment) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Shipment) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Shipment) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Shipment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Shipment) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Shipment) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func init() {
	proto.RegisterType((*Shipment)(nil), "logistics.supplychain.Shipment")
}

func init() {
	proto.RegisterFile("logistics/supplychain/shipment.proto", fileDescriptor_2ccdafbfa7d76829)
}

var fileDescriptor_2ccdafbfa7d76829 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe3, 0x50, 0x42, 0xea, 0x81, 0xc1, 0x12, 0xc8, 0x42, 0x60, 0x55, 0x88, 0xa1, 0x53,
	0x3b, 0x30, 0xb0, 0xb3, 0xb1, 0x96, 0x8d, 0x2d, 0xd8, 0x16, 0x3d, 0x29, 0x89, 0x2d, 0xdf, 0x05,
	0xd1, 0xb7, 0xe0, 0xb1, 0x18, 0x3b, 0x32, 0x21, 0x94, 0xbc, 0x08, 0x8a, 0x9b, 0xa6, 0x65, 0xfc,
	0xfe, 0xfc, 0x4e, 0xa7, 0x8f, 0xdf, 0x95, 0xee, 0x0d, 0x90, 0x40, 0xe3, 0x12, 0x1b, 0xef, 0xcb,
	0x8d, 0x5e, 0x17, 0x50, 0x2f, 0x71, 0x0d, 0xbe, 0xb2, 0x35, 0x2d, 0x7c, 0x70, 0xe4, 0xc4, 0xc5,
	0xd8, 0x5a, 0x1c, 0xb5, 0x6e, 0x7f, 0x18, 0xcf, 0x9f, 0x87, 0xa6, 0x38, 0xe7, 0x29, 0x18, 0xc9,
	0x66, 0x6c, 0x3e, 0x59, 0xa5, 0x60, 0x84, 0xe2, 0x7c, 0x7f, 0xe5, 0xc9, 0xc8, 0x74, 0xc6, 0xe6,
	0xd3, 0xd5, 0x91, 0x23, 0xae, 0xf9, 0xd4, 0x07, 0x67, 0x1a, 0xdd, 0xc7, 0x27, 0x31, 0x3e, 0x18,
	0xe2, 0x92, 0x67, 0x68, 0x6b, 0x63, 0x83, 0x9c, 0xc4, 0x68, 0x50, 0xe2, 0x8a, 0xe7, 0xc1, 0x6a,
	0x0b, 0xef, 0x36, 0xc8, 0xd3, 0x98, 0x8c, 0x3a, 0x32, 0x54, 0x50, 0x83, 0x32, 0x1b, 0x98, 0xa8,
	0x7a, 0xa6, 0x74, 0xba, 0x20, 0x70, 0xb5, 0x3c, 0xdb, 0x31, 0x7b, 0xdd, 0x7f, 0x41, 0x50, 0x59,
	0xa4, 0xa2, 0xf2, 0x32, 0xdf, 0x7d, 0x31, 0x1a, 0x8f, 0x0f, 0x5f, 0xad, 0x62, 0xdb, 0x56, 0xb1,
	0xdf, 0x56, 0xb1, 0xcf, 0x4e, 0x25, 0xdb, 0x4e, 0x25, 0xdf, 0x9d, 0x4a, 0x5e, 0x6e, 0x0e, 0xbb,
	0x7d, 0xfc, 0x5b, 0x8e, 0x36, 0xde, 0xe2, 0x6b, 0x16, 0x77, 0xbb, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xa8, 0x51, 0xe9, 0x80, 0x5f, 0x01, 0x00, 0x00,
}

func (m *Shipment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Shipment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Shipment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Timestamp) > 0 {
		i -= len(m.Timestamp)
		copy(dAtA[i:], m.Timestamp)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.Timestamp)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Location) > 0 {
		i -= len(m.Location)
		copy(dAtA[i:], m.Location)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.Location)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProductId) > 0 {
		i -= len(m.ProductId)
		copy(dAtA[i:], m.ProductId)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.ProductId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ShipmentId) > 0 {
		i -= len(m.ShipmentId)
		copy(dAtA[i:], m.ShipmentId)
		i = encodeVarintShipment(dAtA, i, uint64(len(m.ShipmentId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintShipment(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintShipment(dAtA []byte, offset int, v uint64) int {
	offset -= sovShipment(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Shipment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovShipment(uint64(m.Id))
	}
	l = len(m.ShipmentId)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	l = len(m.ProductId)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	l = len(m.Location)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	l = len(m.Timestamp)
	if l > 0 {
		n += 1 + l + sovShipment(uint64(l))
	}
	return n
}

func sovShipment(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShipment(x uint64) (n int) {
	return sovShipment(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Shipment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShipment
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Shipment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Shipment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShipmentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShipmentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProductId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProductId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Location = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthShipment
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthShipment
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Timestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShipment(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShipment
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShipment(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShipment
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShipment
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShipment
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShipment
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShipment
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShipment        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShipment          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShipment = fmt.Errorf("proto: unexpected end of group")
)
