// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: logistics/supplychain/query.proto

package supplychain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName      = "/logistics.supplychain.Query/Params"
	Query_Product_FullMethodName     = "/logistics.supplychain.Query/Product"
	Query_ProductAll_FullMethodName  = "/logistics.supplychain.Query/ProductAll"
	Query_Shipment_FullMethodName    = "/logistics.supplychain.Query/Shipment"
	Query_ShipmentAll_FullMethodName = "/logistics.supplychain.Query/ShipmentAll"
	Query_Order_FullMethodName       = "/logistics.supplychain.Query/Order"
	Query_OrderAll_FullMethodName    = "/logistics.supplychain.Query/OrderAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Product items.
	Product(ctx context.Context, in *QueryGetProductRequest, opts ...grpc.CallOption) (*QueryGetProductResponse, error)
	ProductAll(ctx context.Context, in *QueryAllProductRequest, opts ...grpc.CallOption) (*QueryAllProductResponse, error)
	// Queries a list of Shipment items.
	Shipment(ctx context.Context, in *QueryGetShipmentRequest, opts ...grpc.CallOption) (*QueryGetShipmentResponse, error)
	ShipmentAll(ctx context.Context, in *QueryAllShipmentRequest, opts ...grpc.CallOption) (*QueryAllShipmentResponse, error)
	// Queries a list of Order items.
	Order(ctx context.Context, in *QueryGetOrderRequest, opts ...grpc.CallOption) (*QueryGetOrderResponse, error)
	OrderAll(ctx context.Context, in *QueryAllOrderRequest, opts ...grpc.CallOption) (*QueryAllOrderResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Product(ctx context.Context, in *QueryGetProductRequest, opts ...grpc.CallOption) (*QueryGetProductResponse, error) {
	out := new(QueryGetProductResponse)
	err := c.cc.Invoke(ctx, Query_Product_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProductAll(ctx context.Context, in *QueryAllProductRequest, opts ...grpc.CallOption) (*QueryAllProductResponse, error) {
	out := new(QueryAllProductResponse)
	err := c.cc.Invoke(ctx, Query_ProductAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Shipment(ctx context.Context, in *QueryGetShipmentRequest, opts ...grpc.CallOption) (*QueryGetShipmentResponse, error) {
	out := new(QueryGetShipmentResponse)
	err := c.cc.Invoke(ctx, Query_Shipment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ShipmentAll(ctx context.Context, in *QueryAllShipmentRequest, opts ...grpc.CallOption) (*QueryAllShipmentResponse, error) {
	out := new(QueryAllShipmentResponse)
	err := c.cc.Invoke(ctx, Query_ShipmentAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Order(ctx context.Context, in *QueryGetOrderRequest, opts ...grpc.CallOption) (*QueryGetOrderResponse, error) {
	out := new(QueryGetOrderResponse)
	err := c.cc.Invoke(ctx, Query_Order_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OrderAll(ctx context.Context, in *QueryAllOrderRequest, opts ...grpc.CallOption) (*QueryAllOrderResponse, error) {
	out := new(QueryAllOrderResponse)
	err := c.cc.Invoke(ctx, Query_OrderAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Product items.
	Product(context.Context, *QueryGetProductRequest) (*QueryGetProductResponse, error)
	ProductAll(context.Context, *QueryAllProductRequest) (*QueryAllProductResponse, error)
	// Queries a list of Shipment items.
	Shipment(context.Context, *QueryGetShipmentRequest) (*QueryGetShipmentResponse, error)
	ShipmentAll(context.Context, *QueryAllShipmentRequest) (*QueryAllShipmentResponse, error)
	// Queries a list of Order items.
	Order(context.Context, *QueryGetOrderRequest) (*QueryGetOrderResponse, error)
	OrderAll(context.Context, *QueryAllOrderRequest) (*QueryAllOrderResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Product(context.Context, *QueryGetProductRequest) (*QueryGetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Product not implemented")
}
func (UnimplementedQueryServer) ProductAll(context.Context, *QueryAllProductRequest) (*QueryAllProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProductAll not implemented")
}
func (UnimplementedQueryServer) Shipment(context.Context, *QueryGetShipmentRequest) (*QueryGetShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shipment not implemented")
}
func (UnimplementedQueryServer) ShipmentAll(context.Context, *QueryAllShipmentRequest) (*QueryAllShipmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShipmentAll not implemented")
}
func (UnimplementedQueryServer) Order(context.Context, *QueryGetOrderRequest) (*QueryGetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
}
func (UnimplementedQueryServer) OrderAll(context.Context, *QueryAllOrderRequest) (*QueryAllOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Product_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Product(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Product_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Product(ctx, req.(*QueryGetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProductAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProductAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ProductAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProductAll(ctx, req.(*QueryAllProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Shipment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Shipment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Shipment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Shipment(ctx, req.(*QueryGetShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ShipmentAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllShipmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ShipmentAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ShipmentAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ShipmentAll(ctx, req.(*QueryAllShipmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Order_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Order(ctx, req.(*QueryGetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OrderAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OrderAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_OrderAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OrderAll(ctx, req.(*QueryAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logistics.supplychain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Product",
			Handler:    _Query_Product_Handler,
		},
		{
			MethodName: "ProductAll",
			Handler:    _Query_ProductAll_Handler,
		},
		{
			MethodName: "Shipment",
			Handler:    _Query_Shipment_Handler,
		},
		{
			MethodName: "ShipmentAll",
			Handler:    _Query_ShipmentAll_Handler,
		},
		{
			MethodName: "Order",
			Handler:    _Query_Order_Handler,
		},
		{
			MethodName: "OrderAll",
			Handler:    _Query_OrderAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logistics/supplychain/query.proto",
}
